### ISSUE TITLE
BrowserslistError: Unknown browser query `dead`

### ISSUE THREAD

**Issue by jraleman** [jraleman/react-cordova-tachyons#1]
I am getting the following error when I run `npm run tachyons`...

This is my output
```
> react-cordova-tachyons@1.0.0 tachyons /home/jraleman/Desktop/react-cordova-tachyons
> node ./node_modules/tachyons-build-css/index.js ./src/themes/tachyons/tachyons.css > ./src/themes/index.css

/home/jraleman/Desktop/react-cordova-tachyons/node_modules/tachyons-build-css/node_modules/caniuse-api/node_modules/browserslist/index.js:37
    throw new BrowserslistError(name);
    ^
BrowserslistError: Unknown browser query `dead`
    at error (/home/jraleman/Desktop/react-cordova-tachyons/node_modules/tachyons-build-css/node_modules/caniuse-api/node_modules/browserslist/index.js:37:11)
    at /home/jraleman/Desktop/react-cordova-tachyons/node_modules/tachyons-build-css/node_modules/caniuse-api/node_modules/browserslist/index.js:222:9
    at Array.forEach (<anonymous>)
    at browserslist (/home/jraleman/Desktop/react-cordova-tachyons/node_modules/tachyons-build-css/node_modules/caniuse-api/node_modules/browserslist/index.js:196:13)
    at cleanBrowsersList (/home/jraleman/Desktop/react-cordova-tachyons/node_modules/tachyons-build-css/node_modules/caniuse-api/dist/utils.js:56:59)
    at setBrowserScope (/home/jraleman/Desktop/react-cordova-tachyons/node_modules/tachyons-build-css/node_modules/caniuse-api/dist/index.js:29:43)
    at Object.<anonymous> (/home/jraleman/Desktop/react-cordova-tachyons/node_modules/tachyons-build-css/node_modules/caniuse-api/dist/index.js:91:1)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)

```

Check  the following snippet:
```
node_modules/tachyons-build-css/node_modules/caniuse-api/node_modules/browserslist/index.js
    throw new BrowserslistError(name);
    ^
    (line 37)
```

Maybe there is something wrong with this dependency?
I tried using the following stater guide, but it seems it doesn't work on my end.

The thing is that when I try to run the `npm run css`, the equivalent of the `taychons` script from this repo, it works fine, from their own git repository.

Any thoughts on this?

**Comment by felromo** [comment]
Yeah seems other have this issue as well.

I ran into a solution here https://github.com/tachyons-css/cli/issues/22
By removing the lines outline in that link we can get npm start to run without any errors and it'll work.
However when we run npm start it'll prompt us with "we're unable to detect target browsers" and if you would like to add the defaults. Now choosing yes will allow us to continue however next time we want to run npm start it'll give us the same error and we have to remove the same line. However if we pick no the script wont run because "as of react-scripts >=2 you must specify targeted browsers"

**Comment by jraleman** [comment]
Thanks Felipe! 
Issue fixed :)
